### ISSUE TITLE
aot error

### ISSUE THREAD

**Issue by KragelNikita** [jgluhov/ng2-spinning-preloader#2]
Hi! first of all thanks for the amazing preloader!
i have a problem, when trying to build my app with aot. And problem is on your preloader.
Can you please change `  constructor(@Inject(DOCUMENT) private document: Document) {
    this.container = this.document.querySelector(CONTAINER_QUERY);
  }`

to the `  constructor(@Inject(DOCUMENT) private document: any) {
    this.container = this.document.querySelector(CONTAINER_QUERY);
  }`

in ng-spinner-preloader.server.ts. This will solve the problem! thank u!

**Comment by jgluhov** [comment]
Fix this issue. take a look at it and please comment.

**Comment by KragelNikita** [comment]
all right!

**Comment by dorianboulch** [comment]
Hi !

It would be great to tag the last version including this fix. 
Would you tag it please ?

Thanks !
